---
- name: Restart apache
  service: name=apache2 state=restarted
- name: reload apache
  service: name=apache2 state=reloaded
- name: Update
  service: name=update

- name: Make sure a service is running
  systemd:
    state: started
    name: httpd
